import Head from "next/head";
import styles from "../styles/Home.module.css";
import { AiOutlineUserAdd } from "react-icons/ai";
import Table from "@/components/Table";
import Form from "@/components/Form";
import { useState } from "react";

export default function Home() {
  const [visible, setVisible] = useState(false);

  const handler = () => {
    setVisible(!visible);
  };
  return (
    <>
      <Head>
        <title>Emoployee Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <main className={styles.main}>
          <h1 className="text-xl md:text-5xl text-center font-extrabold py-10">
            Emoployee Management
          </h1>
          <div className="container mx-auto flex justify-between py-5 border-b">
            <div className="left flex gap-3 px-6">
              <button
                className="flex bg-indigo-500 rounded-md px-2 py-1 cursor-pointer"
                onClick={handler}
              >
                Add Employee
                <AiOutlineUserAdd className="ml-1 mt-1" />
              </button>
            </div>
          </div>

          {visible ? <Form /> : <></>}

          <div className="container mx-auto">{<Table />}</div>
        </main>
      </section>
    </>
  );
}
